version: '3.4'

services:
  dataservice:
    image: ${DOCKER_REGISTRY-}dataservice
    build:
      context: .\DataService
      dockerfile: Dockerfile

  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .\WebApi
      dockerfile: Dockerfile

